@startuml
!define LIGHTRED
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml
actor User
participant Interface
participant PersoPrincipal
participant Ennemi

User -> Interface: Start Game
activate Interface
Interface -> PersoPrincipal: new PersoPrincipal()
activate PersoPrincipal
Interface -> User: Game Started
User -> Interface: Controls
Interface -> PersoPrincipal: update()
PersoPrincipal -> Ennemi: checkCollision()
activate Ennemi
Ennemi -> PersoPrincipal: interact()
deactivate Ennemi
PersoPrincipal -> Interface: updateCompteur()
deactivate PersoPrincipal
Interface -> Interface: Check Game Over
alt Game Over
  Interface -> Interface: endGame()
  User -> Interface: Show Game Over Screen
  else
  Interface -> Interface: Repaint()
end

User -> Interface: Presses B Key
Interface -> Interface: Restart Game
activate Interface
Interface -> PersoPrincipal: Reset game state
PersoPrincipal -> Ennemi: Reset Ennemi positions
activate Ennemi
Ennemi --> PersoPrincipal: Ennemi positions reset
deactivate Ennemi
PersoPrincipal --> Interface: Game state reset
Interface -> Interface: Start Game
deactivate Interface

@enduml
